### ISSUE TITLE
Ties Cannot be Rendered

### ISSUE THREAD

**Issue by cymhellfire** [opensheetmusicdisplay/opensheetmusicdisplay#503] opened 2019-03-26 12:27 UTC
Hi, there.

First, I'd like to thank you all for doing such a good project. But during my test, I found the ties in my piano sheet cannot be rendered as expected.  
Here is the screenshot captured in Sibeilius:  
![Sibelius_Y2iM5KDttv](https://user-images.githubusercontent.com/8386803/54996595-afbcfb80-5004-11e9-926d-e25888e8219f.png)  
And here is the rendering result in OSMD:  
![chrome_8q0FRuphuU](https://user-images.githubusercontent.com/8386803/54996661-dda24000-5004-11e9-9375-742f6eb376bd.png)

As you can see, the tie cross measure 1 and measure 2 is missing. Is this a known issue or I just missed something? Any responding is appreciate, thank you.

PS: Here is my test ```.xml``` file, just take it if you need. [tie.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3008100/tie.zip)

**Comment by cymhellfire** [comment] 2019-03-26 12:36
Here is another test case.  
![chrome_WmrN6oPJ1p](https://user-images.githubusercontent.com/8386803/54997374-87ce9780-5006-11e9-9592-a26b9e993048.png)  
As the screenshot shows, there are two ties rendered correctly. But other ties are not rendered as I mentioned before.  
I also upload the xml here: [Nagisa.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3008140/Nagisa.zip)

**Comment by sschmidTU** [comment] 2019-03-26 22:12
Should be fixed now on the develop branch, will be in the next release.
![image](https://user-images.githubusercontent.com/33069673/55036756-d9355180-501b-11e9-926d-e8ea56f386c1.png)

Nagisa also has all the ties Musescore shows. Here are the last two systems:
![image](https://user-images.githubusercontent.com/33069673/55036909-53fe6c80-501c-11e9-88b5-c4a08dafc8b8.png)

The cause was a malfunctioning dictionary that linked SourceMeasures to GraphicalMeasures. Dictionaries with complex objects as keys don't work well in Typescript, they overwrite the previous values.
That reminds me that i should fix the other Dictionaries of this kind in OSMD, so thank you! I already fixed an error like this once, and now i've seen that there are only a few more dictionaries that might be problematic.

**Comment by cymhellfire** [comment] 2019-03-27 14:09
Glad to hear the bug has been fixed. Thank you for your work!

**Closed** 2019-03-27 15:40 UTC
Labels: bug

**Comment by dlujan** [comment] 2019-08-11 20:19
Has this issue been reverted because the ties in my xml files aren't being rendered.

Sibelius screenshot:
<img width="573" alt="sibelius" src="https://user-images.githubusercontent.com/40183621/62839114-3d635580-bc4b-11e9-83fd-feb51e138fab.png">

osmd screenshot:
![osmd](https://user-images.githubusercontent.com/40183621/62839123-54a24300-bc4b-11e9-8de6-07c2806edbe9.png)
