### ISSUE TITLE
[BUG] - Multiple tempos get all together

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#825] opened 2020-07-06 15:04 UTC
So I have a music that has more than 1 tempo, and they all get smashed together at the top of the first measure.
They should be positioned at the top of the measure the tag is.

```
   <direction>
    <direction-type>
     <metronome default-y="50" color="#000000" font-family="Opus Text Std" font-style="normal" font-size="12.0472" font-weight="normal">
      <beat-unit>quarter</beat-unit>
      <beat-unit-dot />
      <per-minute>60</per-minute>
     </metronome>
    </direction-type>
    <voice>1</voice>
    <staff>1</staff>
   </direction>
```

```
   <direction>
    <direction-type>
     <metronome default-y="30" color="#000000" font-family="Opus Text Std" font-style="normal" font-size="12.0472" font-weight="normal">
      <beat-unit>quarter</beat-unit>
      <per-minute>140</per-minute>
     </metronome>
    </direction-type>
    <voice>1</voice>
    <staff>1</staff>
   </direction>

```

![Captura de tela de 2020-07-06 12-02-37](https://user-images.githubusercontent.com/2137569/86608250-a731cf80-bf80-11ea-8c45-64cc92cc7674.png)

**Comment by sschmidTU** [comment] 2020-07-06 15:11
duplicate of #680. there's an option to disable metronome marks for now, see there.

**Closed by sschmidTU** 2020-07-06 15:11 UTC
