### ISSUE TITLE
Changing style (font etc.)

### ISSUE THREAD

**Issue by sr-verde** [opensheetmusicdisplay/opensheetmusicdisplay#477] opened 2018-12-23 10:15 UTC
Hello guys,
is there any possibility to change the style of the sheet (e.g. font family, font sizes, background…)? Would be pretty awesome to do so… If it is not possible, could anyone give me a hint what could be modified to be able to do so?

Best wishes
Pascua

**Comment by bneumann** [comment] 2018-12-23 13:10
Hi there,

thanks for your interest. @sschmidTU has implement some static theming. Other then that we are still wanting to implement a plugin system which also targets coloring and theming at runtime. BUT this will be not done in the next few releases I am afraid. 
About the hint, check for the options for static coloring and see if you can extent the interface with your preferences. That would also be a cool thing for a PR :)

**Comment by sr-verde** [comment] 2018-12-23 13:16
There is some time between Christmas and the New Year… ¯\_(ツ)_/¯

**Comment by bneumann** [comment] 2018-12-23 13:16
Duplicate of #440 #268 #207

**Comment by bneumann** [comment] 2018-12-23 13:18
@sr-verde that's good. I might have some time as well.

**Comment by sschmidTU** [comment] 2018-12-23 14:16
Just to be clear, take a look at [IOSMDOptions](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/master/src/OpenSheetMusicDisplay/OSMDOptions.ts) (OSMD constructor argument) for some coloring and layouting options.
Font is fixed for now, we could make an option for that as well in OSMDOptions.
Search the code for this:
`this.ctx.setFont("Times New Roman", fontHeight, VexFlowConverter.fontStyle(fontStyle));`

**Comment by sschmidTU** [comment] 2019-09-03 17:07
There is now an OSMDOption to set the FontFamily:
```js
osmd.setOptions({defaultFontFamily: "Helvetica"});
```
The default, as before, is Times New Roman, which the layout and spacing e.g. for lyrics was optimized for.

Screenshot with the default Times New Roman:
![image](https://user-images.githubusercontent.com/33069673/64191618-27773800-ce79-11e9-90e6-d9167f3ad8f1.png)

Screenshot with Helvetica:
![image](https://user-images.githubusercontent.com/33069673/64191644-3362fa00-ce79-11e9-8d98-4c31b5097457.png)

Screenshot with Comic Sans MS (sorry, had to be done):
![image](https://user-images.githubusercontent.com/33069673/64193523-2ea04500-ce7d-11e9-944d-50d8918cc56f.png)

There may still be small optimization issues like lyrics spacing (see blau-e in the screenshot), because these were optimized for the default Times New Roman.

Font size setting will be a little more complicated, because there are many variables for it and there are many ways one could set e.g. the title label and lyrics labels sizes differently, but a general font size multiplicator applied to all labels should be relatively simple.

Since bounding boxes are calculated from GraphicalLabel and e.g. MeasureNumberPlacement creates a GraphicalLabel directly, we could simply insert the multiplicator there.

**Comment by AlbertHart** [comment] 2019-10-26 02:27
Even if you can't easily add font-size, perhaps you can add font weight (e.g. bold)

And I would like to vote for the multiplier.

I have a user case where I am rendering the full score at one zoom, and rendering the score with notes at a smaller zoom because I want to read the chords but do not need to read the notes. But it would be nice to make the chords bold and/or larger at the smaller zoom.

![image](https://user-images.githubusercontent.com/8965352/67613028-3c33c600-f76e-11e9-8413-5ed3b51ec536.png)

**Comment by sschmidTU** [comment] 2023-09-18 19:38
You can now also set `osmd.EngravingRules.DefaultFontStyle = FontStyles.Bold`, for example.

**Closed by sschmidTU** 2023-09-18 19:38 UTC
Labels: feature
