### ISSUE TITLE
Unicode issue when saving PDF

### ISSUE THREAD

**Issue by LearnedLately** [opensheetmusicdisplay/opensheetmusicdisplay#1559] opened 2024-09-13 17:09 UTC
When saving a PDF with Chinese characters in the title (e.g. "您好，我遇到一个解决不了的问题：中文导出PDF格式的情况下，中文部分变成乱码，请问改如何解决"), the text becomes: `¨Y}ÿb•GR0NN*‰ãQ³NN†v„•î˜˜ÿN-e‡[üQúPDFh<_v„`ÅQµNÿN-e‡•èRSØbNqxÿ‹÷•îe9Y‚OU‰ãQ³. In the demo it renders correctly in browser, but somewhere in the process of saving a PDF the title text gets corrupted.

Example .musicxml attached
[PDF_Title_is_garbled.zip](https://github.com/user-attachments/files/16997263/PDF_Title_is_garbled.zip)

**Comment by sschmidTU** [comment] 2024-09-13 17:11
Duplicate of https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1184.

It's a jsPDF limitation.
PDF export is just a feature of our demo, not of the OSMD library, but you can try to fix it as described in the issue above.

**Closed by sschmidTU** 2024-09-13 17:11 UTC
Labels: duplicate
