### ISSUE TITLE
Tuplet numbers should not be rendered in tab staff

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#805] opened 2020-06-22 15:48 UTC
Tuplet numbers are being rendered in the tab staff. If the tab was the type that has stems this might be ok but because there are no stems, seeing a floating number is confusing and non-standard. Especially in the grand staff case like in the image below, those extraneous tuplet numbers nearly look like part of the top staff.

![Screen Shot 2020-06-22 at 11 44 31 AM](https://user-images.githubusercontent.com/44449222/85307359-d246fa00-b47d-11ea-8ca1-bddb3718984d.png)

**Comment by sschmidTU** [comment] 2020-07-02 21:13
could you post a musicxml sample (zipped)? One measure would be enough (you can cut out the rest)
when i write a tuplet in musescore with tabs, it doesn't add the tuplet to the tab for me.
this should be easy to fix though.

**Comment by sschmidTU** [comment] 2020-07-28 18:10
@MilesMorel i couldn't reproduce this, even if i add triplets in the tab it doesn't show them for me, see these samples:
[tab_triplet_test_samples_no_triplet_shown.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4990320/tab_triplet_test_samples_no_triplet_shown.zip)

could you share a sample that reproduces this? (one measure is enough)

Nevertheless, i've added `osmd.EngravingRules.TupletNumbersInTabs`, which is now false by default, so maybe your scores will already be fixed.
Will be in the new release, which should be up very soon.

**Closed** 2020-07-28 18:09 UTC
