### ISSUE TITLE
Click in the note area

### ISSUE THREAD

**Issue by miller06** [opensheetmusicdisplay/opensheetmusicdisplay#1469] opened 2023-10-09 07:04 UTC
Hey，May I ask if there are click events in this area? I would like to click on this area to do some business
![20231009150135](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/e2c021a0-694e-4e83-98a3-3101e7b3c2c8)

**Comment by sschmidTU** [comment] 2023-10-31 20:58
Hi, this is a duplicate of #857.
Unfortunately there is no ready-made click event in public OSMD, that's exclusive to our [sponsor-only audio player](https://github.com/sponsors/opensheetmusicdisplay) for now.
But the information in issue #857 should theoretically be enough to implement them yourself.
Also, sorry for the delay in answering!

**Closed by sschmidTU** 2023-10-31 20:58 UTC
