### ISSUE TITLE
Chord Spacing

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#597] opened 2019-10-23 05:31 UTC
In this score, the Chord letters overlap.

Apparently the measure spacing does not take into account chord letter.

The Rendering scale does not seem to have any effect.

I suppose I could add some fake lyrics to make the measure larger.

Does anyone else have any ideas?

![image](https://user-images.githubusercontent.com/8965352/67360800-17e4a900-f524-11e9-9a80-fe7d25473756.png)

**Comment by AlbertHart** [comment] 2019-10-23 13:42
Adding a dummy lyric did work for now...

![image](https://user-images.githubusercontent.com/8965352/67398911-a3802900-f568-11e9-8634-9fe406e33e32.png)

**Comment by sschmidTU** [comment] 2019-10-23 14:00
Yes, the problem is that we don't have a chord symbol spacing method yet, as we have for lyrics. We rarely see chord symbol overlaps and so many long chord symbols in one measure, though it's of course a valid use case.
It would be great to port the system for lyrics spacing, which also enlargens the measure if there isn't enough space, and apply it to chord symbols.
Actually, as @matt-uib said, it would be great to apply this x-positioning system to all symbols that are on the same y-plane (need x layout), expressions too.

**Comment by AlbertHart** [comment] 2019-10-23 14:30
How do I get this labelled as a feature request (or bug)?

**Comment by sschmidTU** [comment] 2019-10-23 14:38
Best way is asking :) i applied the feature label.
probably not a bug, because chord spacing doesn't exist yet.

**Comment by sschmidTU** [comment] 2019-12-05 15:36
In #599 i wrote a few starting ideas about chord spacing.
We should space chords equally when there's a lot of space available,
and extend the measure to avoid collisions, like the existing lyrics spacing.

![image](https://user-images.githubusercontent.com/33069673/70249820-3e317180-177d-11ea-9fb5-8aee8931a443.png)
[chord_spacing_with_and_without_extending_measure.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3927684/chord_spacing_with_and_without_extending_measure.musicxml.zip)

A simple method to space the symbols using the available space, without extending measures:
Check the remaining space for chords, which is the space until the next StaffEntry if there is one in the measure, or the end of the measure if there's none.
Then, space the chord symbols equidistant by the remaining space, minus the width of the chordsymbols, divided by number of chordsymbols.
This way, two chord symbols over a whole note are half the measure apart.
If there's not enough space (result << 1), use minimal spacing.

For spacing that eliminates collisions like the existing lyrics spacing, we should apply the same principle and extend the measure.

**Comment by bmjcmj** [comment] 2020-12-21 17:48
This problem still not resolved?
I have the same troubles if there is more than one chord in a measure

**Comment by hartman42** [comment] 2021-01-07 07:36
> In #599 i wrote a few starting ideas about chord spacing.
> We should space chords equally when there's a lot of space available,
> and extend the measure to avoid collisions, like the existing lyrics spacing.
> 
> ![image](https://user-images.githubusercontent.com/33069673/70249820-3e317180-177d-11ea-9fb5-8aee8931a443.png)
> [chord_spacing_with_and_without_extending_measure.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3927684/chord_spacing_with_and_without_extending_measure.musicxml.zip)
> 
> A simple method to space the symbols using the available space, without extending measures:
> Check the remaining space for chords, which is the space until the next StaffEntry if there is one in the measure, or the end of the measure if there's none.
> Then, space the chord symbols equidistant by the remaining space, minus the width of the chordsymbols, divided by number of chordsymbols.
> This way, two chord symbols over a whole note are half the measure apart.
> If there's not enough space (result << 1), use minimal spacing.
> 
> For spacing that eliminates collisions, we should apply the same principle like the existing lyrics spacing and extend the measure.
> (see `VexFlowMusicSheetCalculator.calculateMeasureWidthFromLyrics`)

I've played with this a bit... I'm really not that familiar with the project as a whole but did find the function used with lyrics to lengthen the measure and copied it to use for chords.  What's the next step here?  I kinda new to contributing to other projects like this.

**Comment by sschmidTU** [comment] 2021-01-07 16:01
@hartman42 cool! does it work already, can you share a screenshot?
The usual process would be to fork the repository (top right corner on github), commit and push your changes in your forked repository, and then submit a pull request from there (github will probably prompt you on that as soon as you push changes).
Otherwise you could simply share the changed code, but a pull request would make it much easier for us.

**Comment by hartman42** [comment] 2021-01-07 17:22
before:
![image](https://user-images.githubusercontent.com/9059464/103922480-ce10c000-50e1-11eb-8f9e-fa841b03b0b5.png)
after:
![image](https://user-images.githubusercontent.com/9059464/103922596-f4366000-50e1-11eb-837c-e3e28c577728.png)

I just cloned the repo here so I'll work on updating the fork I have today and do a pull.

**Comment by AlbertHart** [comment] 2021-01-08 18:01
This will be great for me.

When this is ready, let me know how I can get a copy. I do not understand these forks, pulls, etc. at all.

**Comment by sschmidTU** [comment] 2021-01-08 18:04
@AlbertHart No problem! We'll put it into the following release let you know :)

**Comment by hartman42** [comment] 2021-01-12 17:27
@sschmidTU 
I added a field to the last entry dictionary to track the width overlap so we now know how much total overlap exists in the measure before it is elongated.  I was wondering if you think that could somehow be used in adjusting the elongation factor.  I see what may be an over-elongation of the measure when the overlap needed is much greater than the current overlap...
#928

**Comment by hartman42** [comment] 2021-01-12 20:10
I also have a fix for chords with multiple degrees... you may have noticed there in my earlier example that the third chord in the first measure is displayed as F#7(#9) as opposed to F#7(add9).  This saves us a bit of space but I wanted to bring it up here for discussion.  Chords with degrees of type "add" show up as comma-separated values in parenthesis.  Alters show up in another set with "alt" in front and subtracts with "omit".

![image](https://user-images.githubusercontent.com/9059464/104366458-68f50a00-54e7-11eb-8125-6caf815b68ae.png)

XML from MuseScore 3:
[ChordSpacingTest.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5804517/ChordSpacingTest.musicxml.zip)

Since this changes the way we're used to seeing chords, I'd like to get a consensus on if we think we ought to add these to the pull request I have open. #928

**Comment by sschmidTU** [comment] 2021-01-12 21:11
About the "add9", that was discussed in #590 (and perhaps partly in #873), and it sounds like you have a good solution. It would be nice to integrate it, though ideally in a separate pull request, to keep the intents and code diffs separate (you could create a separate branch for that).
I'll try to see if i can help out in the implementation in #928, please tell me otherwise when you have progress or the state is mergable. It's looking very promising and useful so far!

**Comment by hartman42** [comment] 2021-01-13 03:56
Okay, that's gonna be tough to look at with the sample I have...

![MultipleDegreesWithoutSpacing](https://user-images.githubusercontent.com/9059464/104404668-35d36a80-5529-11eb-883d-8af1efc0ec07.png)

Let me see if I can come up with a few other samples that will be easier to read without the spacing...

**Comment by sschmidTU** [comment] 2021-01-25 16:18
Mostly fixed in #928 by @hartman42.

New OSMD Function Test - Chord Spacing:
![image](https://user-images.githubusercontent.com/33069673/105732934-49230480-5f31-11eb-9675-2b36a233ffeb.png)

**Closed by sschmidTU** 2021-01-25 16:18 UTC
Labels: feature
