### ISSUE TITLE
graphical elements

### ISSUE THREAD

**Issue by impactcolor** [opensheetmusicdisplay/opensheetmusicdisplay#179] opened 2017-11-22 01:18 UTC
This isn't a bug but just a question.  Where are the graphical elements?  Like if I wanted to create my own theme to color note heads etc and implement some music notation.

**Comment by sebastianhaas** [comment] 2017-11-22 08:50
Hi!

At this time, OSMD relies on [vexflow ](https://github.com/0xfe/vexflow) to do the actual rendering of music symbols.

May I ask what music notation you have in mind? Vexflow actually supports a lot of common symbols and styles, and adding these is often just a question of adding the right middleware in OSMD to translate the MusicXML's contents to the appropriate vexflow rendering instruction.

If you feel like something is missing in Vexflow too, and you don't see a chance to get it in there (e.g. custom elements, tailored to your specific use case), then we can always try and see if there is a way to provide such functionality within OSMD.

Looking forward to hearing from you!

**Comment by impactcolor** [comment] 2017-11-22 21:17
Ok thank you! I'll dig into VexFlow to see how to do it.

**Comment by sebastianhaas** [comment] 2017-11-23 08:51
As I said, I am not sure that is the right approach. If you could elaborate on what your're trying to achieve, I could maybe help you get going faster.

**Comment by impactcolor** [comment] 2017-11-28 07:12
Ok I think I do need some direction after looking into the VexFlow.  What I would like to do is create a different note head for each note.  For example I want to use myimage.svg for the note head of C.  On the VexFlow docs it says that you can give a note head different styles by using setStyle but it doesn't appear you can user any type of graphic.  You can do setStyle FillColor 'orange' but I wanted to do something like setStyle Fill 'myimage.svg'.

**Comment by impactcolor** [comment] 2017-12-18 20:12
Is there away to color the note heads a different color other than black?

**Comment by sebastianhaas** [comment] 2017-12-19 08:55
@matt-uib

**Comment by matt-uib** [comment] 2017-12-19 12:23
dear @impactcolor, to my knowledge Vexflow doesn't offer exchanging the note symbol with another symbol. As you already found out you can change e.g. the color. That works well. Maybe it makes more sense to ask the developers of vexflow directly. Mostly there is a way to change the whole font of musical symbols. You could design maybe a custom font, that will be used for rendering. But i don't know how far Vexflow offers support for using different music symbol fonts. Please get in touch with the Vexflow guys for this.

**Comment by sebastianhaas** [comment] 2017-12-19 12:47
> Is there away to color the note heads a different color other than black?

I think you already answered your question before?

> You can do setStyle FillColor 'orange'

**Comment by impactcolor** [comment] 2017-12-19 19:30
@matt-uib Thank you for the input!

**Comment by impactcolor** [comment] 2017-12-19 22:48
@sebastianhaas Sorry I was pretty vague on that question and thank you for all your help thus far.  My question was how can I add the Vexflow setStyle to an OSMD file.  For example build/ demo.js has an example of music xml files being loaded.  I wanted to add the setStyle fill color to that but I couldn't tell where to do it at in the code.

**Comment by bneumann** [comment] 2017-12-26 08:29
Hi @impactcolor there are some callbacks in the demo code. I could add another drop-down for you and create a new callback where you can set the style.

**Comment by bneumann** [comment] 2017-12-26 08:35
Bummer, I just saw that you can only set the style for individual elements not for e.g. all notes. So that would be a new feature I guess :-(

**Comment by impactcolor** [comment] 2017-12-27 21:10
@bneumann Thanks for looking into it!  Yea that's where I got stuck.  I could see how to do individual notes but not all.

**Comment by bneumann** [comment] 2017-12-28 10:28
Hi @impactcolor,

I digged into the code  a bit more and came up with sort of a solution:
```
// Get all staff entries throughout the document
const numOfStaffEntries = osmdObj.graphic.VerticalGraphicalStaffEntryContainers.length;
const voiceNumber = 1;
// Define new note style
const styleObj = {fillStyle: "black", strokeStyle: "blue"};
// Get all Vexflow notes in all staves
for(let idx = 0; idx < numOfStaffEntries; idx++) {
   const note = osmdObj.graphic.getStaffEntry(idx).vfNotes[voiceNumber];
  // apply new style
   note.setStyle(styleObj);
}
// Re-render document
osmdObj.render();
```
BUT: I think I found a bug here because the vfNotes property returns only 1 note. Applying the style like this also tainted my lines, braces, texts and so on. So there is something wrong I think. There is also no good way to get all the voices in a staff (from what I found), so iterating over all voices needs some a priori knowledge.

Hope that helps

**Comment by bneumann** [comment] 2017-12-28 10:37
Duplicate of #125

**Comment by impactcolor** [comment] 2017-12-28 18:48
@bneumann It does thank you very much.  I'll dig into it some more.

**Comment by rios88** [comment] 2018-02-15 20:05
Hello, first congratulations. I'm trying to color the notes but I can only do it on the staff above. I'm working with piano sheet music. Would there be any way to color the notes of the second staff? Thank you

**Comment by bneumann** [comment] 2018-02-17 07:54
How do you do the coloring? The example above does all staves. 
If you also have a use case for me I could see if I can create a simple theming interface

**Comment by rios88** [comment] 2018-02-17 11:13
When I put the code above only the first staff colors me and if I change voiceNumber it stops working.
I would like to be able to paint on a piano score the pentagram above (that of the right hand) of one color and the pentagram below (that of the left hand) of another color.
Sorry for my English
Thank you

**Comment by bneumann** [comment] 2018-02-17 12:26
Puedes explicar en Español si lo esta mas  fácil. ¿Pentagram esta staffline, si?

**Comment by rios88** [comment] 2018-02-17 12:48
Lo que quiero conseguir es poder poner en una partitura de piano (las partituras de piano tienen dos pentagramas, una para la mano derecha y otra para la mano izquierda), la mano derecha de un color (el pentagrama de arriba) y la mano izquierda de otro (el pentagrama de abajo). Con el código de arriba consigo poner el pentagrama de arriba de un color pero no consigo ponerle color a la de abajo ya que el voiceNumber si lo cambio me deja de funcionar. Además el numOfStaffEntries me da la longitud de las notas pero solo las del pentagrama de arriba (el de la mano derecha).

Lo pongo también en inglés:

What I want to achieve is to be able to put in a piano score (the piano scores have two staves, one for the right hand and one for the left hand), the right hand of one color (the staff above) and the left hand from another (the staff below). With the above code I can put the above staff of one color but I can not put color to the one below because the voiceNumber if I change it stops working. In addition the numOfStaffEntries gives me the length of the notes but only those of the above staff (the one of the right hand).

**Comment by bneumann** [comment] 2018-02-17 18:07
Vale, veo tu problemo. Voy a probarlo maniana. Deberiá funcionarlo con este script :(

**Comment by rios88** [comment] 2018-02-17 23:04
ok, muchas gracias

**Comment by impactcolor** [comment] 2018-02-21 00:14
@bneumann 
Hello y hola! Estoy intentando el codigo que pusistes y tengo un error:  osmObj not defined. 
Estoy intentandolo en build/demo/

**Comment by bneumann** [comment] 2018-02-21 07:06
¿Puedes darme tu code completamente? Probablemente el osmd object tiene un nombre differente en el script de en el demo.

**Comment by rios88** [comment] 2018-02-21 18:34
@bneumann 

Hola pudiste probar el script para las partituras de piano. Yo sigo sin poder colorear el pentagrama de abajo (el de la mano izquierda)

**Comment by rios88** [comment] 2018-02-22 12:48
Hola @bneumann,
conseguí poner color a las notas del segundo pentagrama (el de la mano izquierda). El problema es cuando hay una nota en el pentagrama de arriba y otra en el pentagrama de abajo en la misma posición solo deja colorear la del pentagrama de arriba.

**Comment by impactcolor** [comment] 2018-03-02 22:53
@bneumann Here is part of the code.  It's calling osmObj 

```
/*jslint browser:true */
(function () {
    "use strict";
    var osmdObj;
    // The folder of the demo files
    var folder = "",
```

This is in index.js build/demo
in js console osbdObj says it's not defined.

**Comment by bneumann** [comment] 2018-03-03 06:58
That looks like a transpile of the demo file. But it is not calling the object, just initialising the variable. Can you give me the stack trace of the error?

**Comment by impactcolor** [comment] 2018-03-06 01:09
@bneumann  
Uncaught ReferenceError: osmObj is not defined
    at eval (eval at h.$a (external_contentscript_siteoverlay_bin.js:47), <anonymous>:1:1)
    at gd.h.$a (external_contentscript_siteoverlay_bin.js:47)

VM153:1


(anonymous) | @ | VM153:1
-- | -- | --
  | h.$a | @ | external_contentscri…teoverlay_bin.js:47

**Comment by sschmidTU** [comment] 2019-02-27 00:31
The osmObj is not defined because it's a local variable in a lambda function. after the {}-block it's in it gets deleted. you need to make it a global variable if you want to access it like that.

**Closed by sschmidTU** 2019-02-27 00:31 UTC
Labels: question

**Comment by bneumann** [comment] 2019-02-27 06:12
For reference I added the variable `osmd` to the console in our demo. So you can fiddle around. @sschmidTU we should mention that somewhere obvious (demo page itself) so users can fiddle around in the console

**Comment by sschmidTU** [comment] 2019-02-27 12:12
True. I mentioned the osmd object in the Wiki now, but would be nice in the demo itself.
