### ISSUE TITLE
Is there a note click event

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1217] opened 2022-08-26 14:39 UTC
I want to click the screen and get the information of the clicked notes. Can this be achieved

**Comment by sschmidTU** [comment] 2022-08-26 15:02
Duplicate of #1212. Please search for existing issues and don't open the same issue twice, or I might have to block you from creating issues.

**Closed** 2022-08-26 15:03 UTC

**Comment by zhouxiang233** [comment] 2022-08-26 15:44
I'm really sorry, but I still don't understand how to use it. How can I get my click coordinates in SVG? Can you tell me directly? Thank you very much

**Comment by sschmidTU** [comment] 2022-08-26 15:46
It's explained in #857.

**Comment by zhouxiang233** [comment] 2022-08-26 16:16
![image](https://user-images.githubusercontent.com/86224160/186948418-76a58f7b-b416-4f7a-95e0-dda8b1c0093e.png)
I'm really sorry. I don't understand what these two parameters are. I'm still a novice. Please forgive me
