### ISSUE TITLE
Downward stems collide with lyrics

### ISSUE THREAD

**Issue by npmccallum** [opensheetmusicdisplay/opensheetmusicdisplay#389] opened 2018-09-16 15:37 UTC
The downward stems on Bs and Cs collide with lyrics. Ds also get really close to the lyrics. I suggest increasing the margin between the lyrics and the staff since the margin is pretty tight in general.

**Comment by sschmidTU** [comment] 2018-09-17 14:59
I haven't seen a collision like that. Can you give an example xml and perhaps screenshot?

Actually the stems should never collide with the lyrics, because the lyrics are placed below the bottomline (the bounding boxes). I think.

In Land der Berge from our Demo, the D is far from colliding with the lyrics.
![image](https://user-images.githubusercontent.com/33069673/45631194-ac1b4b80-ba9a-11e8-87c9-68e9110e1d48.png)

We lowered the margin between staff and lyrics because in most cases it looks better that way, and a collision should be very rare.

In physical sheet music editions, the lyrics are often extremely close to the staff, probably to save space, but also so the eyes don't have to wander too much between lyrics and notes.
![image](https://user-images.githubusercontent.com/33069673/45631327-ee448d00-ba9a-11e8-9227-33597fdae1a0.png)

**Comment by npmccallum** [comment] 2018-09-17 15:14
Here is an example that produces collisions:

[kyrie_a.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2389137/kyrie_a.txt)

**Comment by sschmidTU** [comment] 2018-09-17 15:15
@npmccallum There is an EngravingRules.Rules.lyricsYOffsetToStaffHeight. Can you set that when using OSMD? Default value is 3.0.

**Comment by sschmidTU** [comment] 2018-09-17 15:17
Interesting sample, the bounding boxes should usually not collide. Unless someone wants to take that tradeoff to have a shorter lyrics offset.

**Comment by npmccallum** [comment] 2018-09-17 15:34
@sschmidTU If I understand you correctly, you're suggesting a workaround. Is this correct?

I'd really prefer not to work around this due to the large number of small .musicxml files I'll have. I'd like OSMD to either shorten the stems or increase the margin to avoid such collisions without manual intervention.

**Comment by sschmidTU** [comment] 2018-09-17 20:27
The engraving rule would be a workaround, but actually there shouldn't be a workaround necessary.
Because the lyrics should automatically be placed below the Bottomline, that is, below the loest note bounding box (including the stem). If anything, you should be able to give extra spacing beyond avoiding collisions with that engraving rule.
I'll check why the lyrics placement is off in that sample, i've never seen that before.

**Comment by sschmidTU** [comment] 2022-09-01 15:46
This should be fixed now.

@npmccallum I'm not sure how you produced the collision with your sample, it doesn't happen for me, at least with OSMD 1.5.2, before the current fix.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/33069673/187955982-0f76a3c5-edfb-41b3-be57-838bc24c2959.png">

It can however happen in our Beethoven Geliebte sample, if you set `osmd.EngravingRules.LyricsYMarginToBottomLine = 0.0` (in new state/commit on develop branch).
![image](https://user-images.githubusercontent.com/33069673/187956264-94f494b0-0461-4a14-9191-698f49530be5.png)
(although I can currently not get the overlap to appear with this setting in the demo)

That's why `osmd.EngravingRules.LyricsYMarginToBottomLine` is now 0.2 by default (new EngravingRule).

If you have another sample where this happens, please share it and how to reproduce it, and/or we can reopen the issue.

**Closed by sschmidTU** 2022-09-01 15:46 UTC
