### ISSUE TITLE
Double octave shifts are messed up

### ISSUE THREAD

**Issue by ersbeth** [opensheetmusicdisplay/opensheetmusicdisplay#1382] opened 2023-05-20 14:15 UTC
Hello,

First thanks for your awesome dev :)

I tried to import a .mxl file generated from musescore 4. This file contains a simple piano 4 octave scale (hands together) written with 8 shifts and 15 shifts. In musescore it looks like this :
<img width="992" alt="Capture d’écran 2023-05-20 à 16 05 06" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/20892620/d88f0174-dd7c-4b7a-b3a8-cce6bd1ab31a">

However when loaded with osmd I get this result (even from the public demo):
<img width="1134" alt="Capture d’écran 2023-05-20 à 16 07 39" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/20892620/4712eb66-1065-489e-8a19-aa94ca9e8d01">

As you can see the octave shift is messed up at bar 3 on left hand.
I tried several other combinations of shifts on scales, and as soon as I use 15shifts I get problems: either notes on the wrong octave, or the 15shift symbol disappearing.

I looked at other issues but I didn't find any already talking about this, sorry if I missed it.
I hope you will get some time to investigate this.

Best regards

PS: I tried to attach the mxl but sadly it is rejected by github as not supported file format.

**Comment by sschmidTU** [comment] 2023-05-23 17:50
@rlisbeth What is wrong here in your opinion? The only difference I see in bar 3 left hand is that OSMD writes 8va and 15ma instead of 8 and 15.

You can zip your mxl and then drag and drop it here. Or rename the .mxl to .txt maybe, not sure if it works if it's not a text file. (it works with .musicxml).

Also note that I happen to currently be working on octave shifts in #1378.

**Comment by rlisbeth** [comment] 2023-05-24 11:41
Hello @sschmidTU, thanks for your reply,

> The only difference I see in bar 3 left hand is that OSMD writes 8va and 15ma instead of 8 and 15.

Actually the first 5 notes of bar 3 left hand are written one octave too high, if you compare with the musescore sheet:

<img width="483" alt="Capture d’écran 2023-05-24 à 13 31 23" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/20892620/cb8cda46-2c78-4943-a158-79967ddf5524">
<img width="524" alt="Capture d’écran 2023-05-24 à 13 31 10" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/20892620/409eda99-d01c-4aad-a816-652632ee53ca">

It looks like these notes don't take into account the 8va annotation and thus are written at their "normal" places.

> You can zip your mxl and then drag and drop the zip here

Done :)
[Scale_sixteenth.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11554062/Scale_sixteenth.mxl.zip)

> demo updates on next release, should be in the next few days

Ok I'll check with it as soon as it is available

Best regards

**Comment by sschmidTU** [comment] 2023-05-24 11:59
@rlisbeth Oh, you're absolutely right, I overlooked the wrong octave, sorry!
Thanks for adding the sample.
What's strange is that I can't reproduce this into a minimal sample like this one, which renders fine:
<img width="389" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/1148f333-d1d7-4580-85e3-473e9777b72b">

[test_octaveshift_octave_start_off_beat3.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11554245/test_octaveshift_octave_start_off_beat3.zip)

It seems to be an edge case and interaction with other elements of the score.
I'll try to look into it.

**Comment by sschmidTU** [comment] 2023-05-24 15:13
Fixed in #1386.
<img width="276" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b127b3c0-50d4-4ad2-bc02-c0daa50317cd">

Thanks for the report!

**Closed as completed** 2023-05-24 15:13 UTC
Labels: bug
