### ISSUE TITLE
advance green bar

### ISSUE THREAD

**Issue by davidsancal** [opensheetmusicdisplay/opensheetmusicdisplay#376] opened 2018-09-07 23:01 UTC
I was trying out a score of my own and when I gave it to him to advance the green bar I see that he does not do it well. Attached video

[bug.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2362738/bug.zip)

**Comment by davidsancal** [comment] 2018-09-09 14:00
If it helps you in version 0.2 it works well

**Comment by sschmidTU** [comment] 2018-09-09 16:42
Yes, i noticed this is a regression.
It might be introduced by one of my changes. I'll look into it.

**Comment by davidsancal** [comment] 2018-09-09 17:50
I have been testing and not only fails with silences. I attached another video
[bug2.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2364494/bug2.zip)

**Comment by bneumann** [comment] 2018-09-09 18:33
It's just as I thougth. So the first time the cursor is highlighted is at the position of the whole rest:
![image](https://user-images.githubusercontent.com/2605131/45267557-1dda1080-b46f-11e8-9d5a-78c0f41cbde0.png)

Going to the next note:
![image](https://user-images.githubusercontent.com/2605131/45267561-2e8a8680-b46f-11e8-9a88-88cb58feaa58.png)
And the next...
![image](https://user-images.githubusercontent.com/2605131/45267564-38ac8500-b46f-11e8-9afc-74d274254da8.png)

I am not sure actually what the wanted behaviour is. Is the cursor supposed to stick to the rest note in the first staffline or is it always following the "minimal" voice entries? I assume it is the latter so that would mean that our First staffentry is calculated incorrect. It needs to include the whole rest and the first rest but set the coordinate to the first rest.

**Comment by sschmidTU** [comment] 2018-09-10 12:05
Yes, the cursor needs to always go to the note that will be played next, that is, the smallest next note across all connected StaffLines.
Bach Air is a good example, as I said in the PR.

The bug from "bug2.zip" david posted is fixed in the PR, here's the reproduced score:
[cursor_test_bug2.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2366499/cursor_test_bug2.zip)

**Comment by sschmidTU** [comment] 2018-09-10 22:13
Duplicate of #138 by the way.

**Closed** 2018-09-11 05:11 UTC
