### ISSUE TITLE
Multiple tempos aslo get all together

### ISSUE THREAD

**Issue by yogaliu** [opensheetmusicdisplay/opensheetmusicdisplay#1393] opened 2023-06-09 09:05 UTC
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/15954570/bae615ce-bb05-4ab8-ac1a-ad4780a5a779)
[Beethoven_-_Fr_Elise_-_For_Elise_-_WoO_59_for_piano_solo.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11704419/Beethoven_-_Fr_Elise_-_For_Elise_-_WoO_59_for_piano_solo.mxl.zip)

#680 #825 

Has this issue not been resolved yet?

**Comment by sschmidTU** [comment] 2023-06-09 10:35
test

**Comment by sschmidTU** [comment] 2023-07-27 20:36
Fixed now.

<img width="568" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/ce87e36d-fa6a-4c3a-996e-038d0f7471ff">

The issue is that your sample has way too many metronome marks, which doesn't make sense musically, at least not for standard pieces like in Beethoven to change the metronome mark by +-2 every measure.
For samples like this, I would suggest not rendering metronome marks at all via `osmd.EngravingRules.MetronomeMarksDrawn = false`.
Also, some measures have multiple metronome marks in the MusicXML file.

Also note that the sample also has <sound> attributes, which can also be treated as metronome marks, and are usually only relevant for playback. And their value can be subtly different from the mark (e.g. 61.998 vs 62). Though that's a detail for implementation.

**Closed by sschmidTU** 2023-07-27 20:36 UTC
