### ISSUE TITLE
Missing double bar at end of composition - how do I get it to show up?

### ISSUE THREAD

**Issue by 5t33** [opensheetmusicdisplay/opensheetmusicdisplay#1522] opened 2024-03-11 03:16 UTC
Here's my OSMD config.
```
    const osmdInstance = new OSMD.OpenSheetMusicDisplay(div, {
        autoResize: false,
        backend: backend,
        pageBackgroundColor: "#FFFFFF",
        pageFormat: this.pageFormat,
        drawTitle: true,
        drawTimeSignatures: this.includeTimeSig,
        drawMeasureNumbers: false,
        drawFingerings: true,
        drawCredits: false,
        drawPartNames: false,
        stretchLastSystemLine: true,
        disableCursor: false,
        drawingParameters: this.drawingParameters,
        newPageFromXML: true,
        drawComposer: true,
        newSystemFromXML: true
    });
   osmdInstance.EngravingRules.BetweenStaffDistance = 2
    osmdInstance.EngravingRules.BetweenStaffLinesDistance = 2
    osmdInstance.EngravingRules.SheetMaximumWidth = 32767
    osmdInstance.EngravingRules.PageHeight = 1440
    osmdInstance.EngravingRules.TitleTopDistance = 5.0
    osmdInstance.EngravingRules.TitleBottomDistance = 15
    osmdInstance.EngravingRules.SystemLeftMargin = 5
    osmdInstance.EngravingRules.SystemRightMargin = 5
    osmdInstance.EngravingRules.SheetComposerHeight = 2
    osmdInstance.EngravingRules.NewSystemAtXMLNewSystemAttribute = true
    osmdInstance.DrawingParameters.drawSelectionEndSymbol = true
```

Musescore seems to recognize the end and add the double bars so I think the musicxml is correct...

**Comment by sschmidTU** [comment] 2024-03-11 22:41
Hi, can you share your MusicXML sample? You can either rename it to .txt or zip it and drop it here.
It's hard to say what the issue is without knowing which samples it happens in.

**Comment by 5t33** [comment] 2024-03-11 23:29
here it is
```
<?xml version="1.0" encoding='UTF-8' standalone='no' ?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.0">
 <work>
  <work-title>Mary Had a Little Lamb</work-title>
 </work>
 <identification>
  <creator type="composer">Traditional
arr. Steven Gizzi</creator>
  <rights>Copyright © </rights>
  <encoding>
   <encoding-date>2024-02-18</encoding-date>
   <encoder>Steven Gizzi</encoder>
   <software>Sibelius 20.6.0</software>
   <software>Direct export, not from Dolet</software>
   <encoding-description>Sibelius / MusicXML 3.0</encoding-description>
   <supports element="print" type="yes" value="yes" attribute="new-system" />
   <supports element="print" type="yes" value="yes" attribute="new-page" />
   <supports element="accidental" type="yes" />
   <supports element="beam" type="yes" />
   <supports element="stem" type="yes" />
  </encoding>
 </identification>
 <defaults>
  <scaling>
   <millimeters>215.9</millimeters>
   <tenths>1233</tenths>
  </scaling>
  <page-layout>
   <page-height>1596</page-height>
   <page-width>1233</page-width>
   <page-margins type="both">
    <left-margin>85</left-margin>
    <right-margin>85</right-margin>
    <top-margin>85</top-margin>
    <bottom-margin>85</bottom-margin>
   </page-margins>
  </page-layout>
  <system-layout>
   <system-margins>
    <left-margin>67</left-margin>
    <right-margin>0</right-margin>
   </system-margins>
   <system-distance>120</system-distance>
  </system-layout>
  <appearance>
   <line-width type="stem">1.25</line-width>
   <line-width type="beam">5</line-width>
   <line-width type="staff">1.25</line-width>
   <line-width type="light barline">1.5625</line-width>
   <line-width type="heavy barline">5</line-width>
   <line-width type="leger">1.5625</line-width>
   <line-width type="ending">1.5625</line-width>
   <line-width type="wedge">1.25</line-width>
   <line-width type="enclosure">1.5625</line-width>
   <line-width type="tuplet bracket">1.25</line-width>
   <line-width type="bracket">5</line-width>
   <line-width type="dashes">1.5625</line-width>
   <line-width type="extend">0.9375</line-width>
   <line-width type="octave shift">1.5625</line-width>
   <line-width type="pedal">1.5625</line-width>
   <line-width type="slur middle">1.5625</line-width>
   <line-width type="slur tip">0.625</line-width>
   <line-width type="tie middle">1.5625</line-width>
   <line-width type="tie tip">0.625</line-width>
   <note-size type="cue">75</note-size>
   <note-size type="grace">60</note-size>
  </appearance>
  <music-font font-family="Helsinki Std" font-size="19.8425" />
  <word-font font-family="Palatino" font-size="11.9365" />
  <lyric-font font-family="Palatino" font-size="11.4715" />
  <lyric-language xml:lang="en" />
 </defaults>
 <credit page="1">
  <credit-words default-x="616" default-y="155" font-family="Palatino" font-style="normal" font-size="22.0128" font-weight="normal" justify="center" valign="middle">Mary Had a Little Lamb</credit-words>
 </credit>
 <credit page="1">
  <credit-words default-x="1148" default-y="84" font-family="Palatino" font-style="normal" font-size="11.0064" font-weight="normal" justify="right" valign="middle">Traditional
arr. Steven Gizzi</credit-words>
 </credit>
 <part-list>
  <part-group type="start" number="1">
   <group-symbol>brace</group-symbol>
  </part-group>
  <score-part id="P1">
   <part-name>Piano</part-name>
   <part-name-display>
    <display-text>Piano</display-text>
   </part-name-display>
   <part-abbreviation>Pno.</part-abbreviation>
   <part-abbreviation-display>
    <display-text>Pno.</display-text>
   </part-abbreviation-display>
   <score-instrument id="P1-I1">
    <instrument-name>Piano (2)</instrument-name>
    <instrument-sound>keyboard.piano.grand</instrument-sound>
    <solo />
    <virtual-instrument>
     <virtual-library>Sibelius 6 Essentials</virtual-library>
     <virtual-name>Concert Piano Lite (GPO)</virtual-name>
    </virtual-instrument>
   </score-instrument>
  </score-part>
  <part-group type="stop" number="1" />
 </part-list>
 <part id="P1">
  <!--============== Part: P1, Measure: 1 ==============-->
  <measure number="1" width="318">
   <print new-page="yes">
    <system-layout>
     <system-margins>
      <left-margin>22</left-margin>
      <right-margin>0</right-margin>
     </system-margins>
     <top-system-distance>218</top-system-distance>
    </system-layout>
    <staff-layout number="2">
     <staff-distance>90</staff-distance>
    </staff-layout>
   </print>
   <attributes>
    <divisions>256</divisions>
    <key color="#000000">
     <fifths>0</fifths>
     <mode>major</mode>
    </key>
    <time color="#000000">
     <beats>4</beats>
     <beat-type>4</beat-type>
    </time>
    <staves>2</staves>
    <clef number="1" color="#000000">
     <sign>G</sign>
     <line>2</line>
    </clef>
    <clef number="2" color="#000000">
     <sign>F</sign>
     <line>4</line>
    </clef>
    <staff-details number="1" print-object="yes" />
    <staff-details number="2" print-object="yes" />
   </attributes>
   <note print-object="no" default-x="73">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="73" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="135" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="195" default-y="-40">
    <pitch>
     <step>G</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="257" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 2 ==============-->
  <measure number="2" width="240">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="76" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="137" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>half</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 3 ==============-->
  <measure number="3" width="240">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="75" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="137" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>half</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 4 ==============-->
  <measure number="4" width="240">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="76" default-y="-10">
    <pitch>
     <step>D</step>
     <octave>4</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="137" default-y="-10">
    <pitch>
     <step>D</step>
     <octave>4</octave>
    </pitch>
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>half</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note print-object="no" default-x="76">
    <rest />
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <staff>2</staff>
   </note>
   <note print-object="no" default-x="137">
    <rest />
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>half</type>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 5 ==============-->
  <measure number="5" width="315">
   <print new-system="yes">
    <system-layout>
     <system-margins>
      <left-margin>22</left-margin>
      <right-margin>0</right-margin>
     </system-margins>
     <system-distance>120</system-distance>
    </system-layout>
    <staff-layout number="2">
     <staff-distance>90</staff-distance>
    </staff-layout>
   </print>
   <attributes>
    <staff-details number="1" print-object="yes" />
    <staff-details number="2" print-object="yes" />
   </attributes>
   <note print-object="no" default-x="57">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="57" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="121" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="186" default-y="-40">
    <pitch>
     <step>G</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="250" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 6 ==============-->
  <measure number="6" width="272">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="79" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="143" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="208" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 7 ==============-->
  <measure number="7" width="272">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="79" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="143" default-y="-30">
    <pitch>
     <step>B</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
   <note color="#000000" default-x="207" default-y="-35">
    <pitch>
     <step>A</step>
     <octave>3</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>2</staff>
   </note>
  </measure>
  <!--============== Part: P1, Measure: 8 ==============-->
  <measure number="8" width="180">
   <attributes />
   <note print-object="no" default-x="15">
    <rest />
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>whole</type>
    <staff>1</staff>
   </note>
   <barline>
    <bar-style>light-heavy</bar-style>
   </barline>
   <backup>
    <duration>1024</duration>
   </backup>
   <note color="#000000" default-x="15">
    <pitch>
     <step>G</step>
     <octave>3</octave>
    </pitch>
    <duration>1024</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>whole</type>
    <staff>2</staff>
   </note>
  </measure>
 </part>
</score-partwise>
```

**Comment by sschmidTU** [comment] 2024-03-11 23:43
Fixed.

<img width="177" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/9c5cbd9a-b716-4541-8d11-0f938a37ada3">

The barline element didn't have `location="right"`set, but apparently the attribute is not required and the default value is right, which we didn't set.

Just running some tests before committing.
The next release with this fix should come soon.

**Comment by 5t33** [comment] 2024-03-11 23:48
oh fantastic, thank you!

**Comment by sschmidTU** [comment] 2024-03-11 23:58
Visual regression tests are fine, caught the same issue in 2 more files.
[visual_diff_endbar_locationright.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14565521/diff_endbar_locationright.zip)

Fix committed.

**Closed by sschmidTU** 2024-03-11 23:58 UTC
