### ISSUE TITLE
OSMD will lost octave shift sign and part of slur  by different viewport width

### ISSUE THREAD

**Issue by DavidQinqianWu** [opensheetmusicdisplay/opensheetmusicdisplay#634] opened 2019-12-18 10:19 UTC
I found an interesting thing when I use the OSMD Options: 
drawFromMeasureNumber,
drawUpToMeasureNumber,
and OSMD seems will lost octave shift sign, and missing part of the slur, when I have different viewport width
this is my OSMD Options: 
`this.osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay(this.containerDiv, {
		drawTitle: false,
		drawSubtitle: false,
		drawComposer: false,
		drawCredits: false,
		drawPartNames: false,
		fillEmptyMeasuresWithWholeRest: 0,
		drawFromMeasureNumber: 28,
		drawUpToMeasureNumber: 32
	}); `
This one is when the viewport width is 640 px, which is perfect, and did not lost anything 
![截屏2019-12-18下午6 08 52](https://user-images.githubusercontent.com/23088138/71077249-089b7800-21c2-11ea-95f9-be1fc7d16926.png)
This one is viewport  width is 955px ( lost part of octave shift information)
![截屏2019-12-18下午6 09 28](https://user-images.githubusercontent.com/23088138/71077285-1a7d1b00-21c2-11ea-9e38-fe18245269da.png)
This one is viewport width is: 1381px (lost all octave shift information, and part of slur)
![截屏2019-12-18下午5 59 44](https://user-images.githubusercontent.com/23088138/71077338-31bc0880-21c2-11ea-9fcc-2344ce12bcc4.png)

just wondering that OSMD has this issue is because I use it in wrong way, or I set up something by mistakes?? 
here is my sample
[45.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3977829/45.musicxml.zip)

**Comment by DavidQinqianWu** [comment] 2019-12-19 06:37
According to code in VexFlowMusicSheetDrawer.ts line 293, when the notes in octave shift sign (these notes are in one line).  the` starX` which is smaller than `startY`, so  the  `headroom ===Inifinity` . and `startX` and `startY` are from vexflow. So, is it something wrong within Vexflow?

**Comment by sschmidTU** [comment] 2023-05-17 01:07
Seems to be fixed in #1378 (`fix/octaveshift-multiline-not-ending-at-measure-end` branch, should soon be merged).
Otherwise please add instructions to reproduce on that branch.
We also prevented the infinity bug, and the situation does not seem to occur anymore anyways.

**Closed by sschmidTU** 2023-05-17 01:07 UTC
