### ISSUE TITLE
Faulty Xmls from Sibelius/GuitarPro error on render

### ISSUE THREAD

**Issue by g30225579** [opensheetmusicdisplay/opensheetmusicdisplay#1450] opened 2023-08-23 01:21 UTC
GuitarPro/Sibelius exported
```js
osmdInstance = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
osmdInstance
        .load("./someone.xml")
        .then(
            function () {
                osmdInstance.render();
            }
        );
```
console error: 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'graphicalVoiceEntries')
or
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'MeasureNumber')

[compressed.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12414210/compressed.zip)

Thanks.

**Comment by sschmidTU** [comment] 2023-08-24 17:18
The errors are now fixed.
The issue is that your MusicXML files are faulty, which is unfortunately common with GuitarPro (and to a lesser extent, Sibelius).
There are multiple pedal starts before a pedal end, dynamics are duplicated, etc.
I would try to check if there is a newer GuitarPro version, someone else already asked them to fix their MusicXML export.

**Closed by sschmidTU** 2023-08-24 17:18 UTC
