### ISSUE TITLE
Can we use plug-ins to render the numbered musical notation

### ISSUE THREAD

**Issue by yibo7** [opensheetmusicdisplay/opensheetmusicdisplay#1040] opened 2021-07-04 07:42 UTC
Can we use plug-ins to render the numbered musical notation

**Comment by sschmidTU** [comment] 2021-07-04 12:25
No. Duplicate of #698 .

There was someone implementing Jianpu notation for OSMD, Misko Lee, but he didn't make it public. He posted screenshots in Discord.
![image](https://user-images.githubusercontent.com/33069673/124384874-98851200-dcd3-11eb-9a62-3e04a9708270.png)

**Closed by sschmidTU** 2021-07-04 12:25 UTC
