### ISSUE TITLE
How re-render the display based on key

### ISSUE THREAD

**Issue by dwarka-code** [opensheetmusicdisplay/opensheetmusicdisplay#886] opened 2020-09-17 04:06 UTC
Current if i load XML it start with default key D but i want to switch it to E and render the display with this key

**Comment by ifredom** [comment] 2020-09-18 07:56
change options, then  call render function

**Comment by sschmidTU** [comment] 2020-09-18 13:36
This is called Transposing. Duplicate of #733 .

**Closed by sschmidTU** 2020-09-18 13:36 UTC

**Comment by dwarka-code** [comment] 2020-09-19 10:44
guys can you give simple code how I can change the key and render based on key

**Comment by sschmidTU** [comment] 2021-04-20 19:12
The OSMD Transposition plugin is now integrated into OSMD, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/733#issuecomment-823530818.
(currently on the develop branch, will be released in the next OSMD version after 0.9.5)
