### ISSUE TITLE
Triplet numbers/beams shouldn't be rendered in stemless guitar tablature (SVG backend)

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#851] opened 2020-08-02 17:01 UTC
Great work on getting guitar/bass tablature supported! Here is one thing I've noticed now that I've worked with it a lot:

Traditional (stemless) guitar tablature doesn't include triplet numbers/beams, but they are currently rendered in the stemless tab staves for the SVG backend. 

In the canvas backend, tablature is currently rendered with stems (where beaming and triplet numbers are expected) so this is only an issue with the SVG backend from what I can see.

The effect on UX is that a significant amount of visual noise can be added to the score when rendering with a grand-staff, as is quite common in guitar music. 

Keep up the great work and best wishes all around!

![image](https://user-images.githubusercontent.com/44449222/89127822-ca3b9a80-d4be-11ea-8800-02fc29f4e983.png)

**Comment by sschmidTU** [comment] 2020-08-03 15:21
this seems to be a duplicate of #805.

@MilesMorel i couldn't reproduce this issue. Could you share a sample musicxml that reproduces this?

**Closed** 2023-07-04 17:01 UTC
Labels: Tabs
