### ISSUE TITLE
midi to music xml

### ISSUE THREAD

**Issue by jsphweid** [opensheetmusicdisplay/opensheetmusicdisplay#206] opened 2018-02-26 02:54 UTC
Hi there,

as far as I can tell there isn't any support in this project for inputing midi files but maybe I missed something?

Of course midi is not about making sheet music whereas musicxml is, but I was wondering if anyone knew of a tool to scaffold raw midi to music xml?

I found this site: http://flashmusicgames.com/midi/mid2xml.php but after uploading a simple midi file, osmd could not parse it; it's not valid.

**Comment by bneumann** [comment] 2018-02-26 07:02
Hi,
It looks like the page you posted is converting the midis to something called "midi XML", which I personally have never heard about.
Regarding importing midi files directly, I think @mat-uib mentioned something lately. But yes would be nice to have

**Comment by matt-uib** [comment] 2018-03-25 14:34
after we have implemented a plugin infrastructure for adding plugins to OSMD, we want to build plugins and services on top of that which can be licensed. We will provide a midi importer for rendering the notation of midi files. It will only provide the score rendering - currently no export to musicXML is planned. Maybe this might be another plugin to offer.

**Comment by sschmidTU** [comment] 2023-09-18 19:50
Out of scope of this project.
There are various midi to musicxml converters, though none in javascript as far as I know, unfortunately.
Except for this one which seems abandoned:
https://github.com/turnerhayes/midixmljs

There is also one for Java:
https://github.com/kaibadash/midi2musicxml

The issue is that midi is not made to be displayed, so almost always midi scores look terrible when viewed as sheet music.

**Closed by sschmidTU** 2023-09-18 19:50 UTC
Labels: enhancement, question

**Comment by kamshory** [comment] 2023-10-05 06:22
I just develop MIDI to Music XML on https://github.com/kamshory/PHPMusicXML but not ready yet. Music duration longer than expected.

**Comment by sschmidTU** [comment] 2023-10-05 09:12
@kamshory Nice! Please keep us updated, thanks!

**Comment by kamshory** [comment] 2023-10-19 00:31
For simple music, https://github.com/kamshory/PHPMusicXML can convert music from MIDI to MusicXML.

**Comment by kamshory** [comment] 2026-04-26 12:14
> [@kamshory](https://github.com/kamshory) Nice! Please keep us updated, thanks!

I just updated PHPMusicXML and successfully converted MIDI to MusicXML, but there are still a few issues. It's sufficient for visual rendering, but playing it back as audio still requires some tweaking, especially on channels 10 and 16.
