### ISSUE TITLE
Release non working

### ISSUE THREAD

**Issue by mdan312** [opensheetmusicdisplay/opensheetmusicdisplay#243] opened 2018-04-21 17:52 UTC
I have an error in both Chrome and Edge when including last release of osmd.min.js
The 'Usage' described in https://opensheetmusicdisplay.org/usage/script/ is not working (using OpenSheetMusicDisplay as global library via script tag)

1. opensheetmusicdisplay.min.js -> osmd.min.js (name differs)
2. Error in osmd.min.js (buggy?)
3. Error: opensheetmusicdisplay is not defined (in  osmd.min.js ?)
4. container-id ??

I miss something... Could you help me? The demo is working fine.

**Comment by bneumann** [comment] 2018-04-21 18:10
Looks like a duplicate of #241, see if the latest dev solves your problem. We are currently planning a new release and the docs differ a lot at the moment unfortunately

**Comment by mdan312** [comment] 2018-04-21 18:27
OK Great. I wait a bit for the new release then. Will it include the Vextab transcription feature?

**Comment by matt-uib** [comment] 2018-04-21 20:39
as commented in #244, unfortunately we don't have a Vextab transcription feature

**Comment by global2alex** [comment] 2018-04-24 14:45
Any update on this issue?

**Comment by bneumann** [comment] 2018-04-24 18:27
We are working on it. So far it looks good, but we change a lot of infrastructure and the last release was a year ago so it might take a few more days :)

**Comment by bneumann** [comment] 2018-05-04 10:50
So the new release 0.3.0 is out.

**Comment by global2alex** [comment] 2018-05-04 13:30
@bneumann Great, just in time for the weekend. Thanks.

**Comment by bneumann** [comment] 2018-05-04 14:46
@global2alex have fun ;) let me know if it works now for you

**Closed by bneumann** 2018-05-04 14:46 UTC
