### ISSUE TITLE
Staffentry offset in first measure is not aligned to cursor

### ISSUE THREAD

**Issue by davidsancal** [opensheetmusicdisplay/opensheetmusicdisplay#271] opened 2018-06-18 15:13 UTC
When you arrive with the green bar at the end of the staff and you give a following to make the line jump to the next staff, the first note of this is skipped. 

Attached compressed video
[bug.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2111839/bug.zip)

**Comment by bneumann** [comment] 2018-06-18 16:19
Wow, thanks for the great video report. I think I know what this might be. I have a similar issue with the lyrics. Somehow the first measure has some kind of offset. I will have a look into it as soon as possible

**Comment by PieterHartzer** [comment] 2018-06-25 21:28
I noticed this as well.  It would appear as if the first stave line has the time signature and the rest does not, so it causes the cursor to be out by the width of the time signature for the first note, and then slowly correct itself (averaged?).

**Comment by bneumann** [comment] 2018-06-26 10:31
Is it correcting again? I thought it's correct from the second measure onwards. I already applied an offset in the first measure using vexflows getinstructionwidth

**Comment by PieterHartzer** [comment] 2018-06-26 11:06
The following is what happens once it goes to the new line.  The cursor starts too far to the right by about the width of the time signature.  Then slowly appears to catch up and almost at the end (second last image) it skips a note, and then appears to be correct.
![osmd_1](https://user-images.githubusercontent.com/1129284/41907332-6b1f1092-7938-11e8-8645-b39e0fa29970.JPG)
![osmd_2](https://user-images.githubusercontent.com/1129284/41907338-6d459d64-7938-11e8-875f-84169851af38.JPG)
![osmd_3](https://user-images.githubusercontent.com/1129284/41907340-6e82e2c2-7938-11e8-8a96-d43748166774.JPG)
![osmd_4](https://user-images.githubusercontent.com/1129284/41907341-6fc9d398-7938-11e8-892d-93e48d044d2e.JPG)

I am still trying to get to know the code and couldn't look into it and be of any more help.

**Comment by PieterHartzer** [comment] 2018-06-27 19:57
I deleted my previous comment after realising that there is a separate ticket for the jumping of the cursor - #138 and it's not related tot he padding.
You are correct.  It is only the first measure that had the issue where it was not padded.

**Comment by bneumann** [comment] 2018-06-27 19:59
Hmm that was before I joined. True, I will mark it

**Comment by bneumann** [comment] 2018-06-27 19:59
Duplicate of #138

**Comment by PieterHartzer** [comment] 2018-06-27 21:41
@bneumann I think you misunderstood.  This bug (#271) is related to the misalignment of the cursor in the first measure in a new line staff (when it does not have a time signature).  
#138 Is to do with the cursor skipping notes.  They appear to be separate issues, but at first I thought they were related.

**Comment by bneumann** [comment] 2018-06-29 06:18
Hi, yeah you're righto. But the are still somehow related in the way that we are not correctly setting the staffentry positions in our model. They are derived from the vexflow stavenotes but something is fishy there.

**Comment by sschmidTU** [comment] 2018-07-24 15:52
Seems to be fixed now. The cursor is still not always completely accurate, but that's different issues.
![image](https://user-images.githubusercontent.com/33069673/43150281-d18a5534-8f69-11e8-95db-225bc820b801.png)

For reference, this is the misalignment from the video posted in the first comment:
![image](https://user-images.githubusercontent.com/33069673/43150424-31120e0c-8f6a-11e8-88f4-5feca236e79f.png)

**Closed by sschmidTU** 2018-07-24 15:52 UTC
Labels: bug
