### ISSUE TITLE
Horizontal alignment issues with transposing parts

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1425] opened 2023-07-12 04:29 UTC
Here is another issue that should be fixed, and I am wondering if there is an easy fix for it.

When a score includes transposing parts (which results in parts having different key signatures), the music is not correctly aligned horizontally.

Have a look at the screenshot below, I have circled the bar where the problem is mostly shown, the notes of the first and second part are not aligned because of the different key signature:

![clarShot](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/ddb72bac-621e-433c-b16b-3c45c53cb23d)

Similarly, look at this shot of a score with multiple instruments; again, I have circled in red where the problem is mostly shown, the "Violin piccolo in Eb" part is even going out of the bar line on the right:

![brandShot](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/d1f207ba-c3c8-4691-92c7-e8b5390e91f0)

I have taken those shots from the demo page:

https://opensheetmusicdisplay.github.io/demo/

And you can try yourself with the same files from the link below:

[OSMD_transp_examples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12043371/OSMD_transp_examples.zip)

All parts should be horizontally aligned from the time signature by starting from the most-far-right time signature (in the case of the last score above, aligned with the "Violin piccolo in Eb" part).

I am eager to know if there is a way to fix that or if you plan to fix that. I have spent hours trying to figure out and fix the code myself, but it looks like it'd be almost impossible for me to do it. I guess who wrote the code should be able to do it faster or point me in the right direction?

Thank you!

All the best,

**Comment by sschmidTU** [comment] 2023-07-12 09:00
Duplicate of #1315.
We would definitely like to fix that soon!
One possibility is looking at how Vexflow 4 fixed it. But I think we should be able to figure this out on our own as well.

**Comment by fablau** [comment] 2023-07-12 15:13
Wow, thank you so much Simon! If you can fix that, that'd be great! I have really spent a week trying to figure that out myself, and I am glad I asked about it.

Looking forward for it! ;)

**Comment by joshstovall** [comment] 2023-07-13 04:59
This would be an epic update. 🙏 I tried one day for an hour or so to find a fix but was not yet familiar enough to implement a solution. 

This is probably the top on my list, and really the only thing, that prevents OSMD scores from looking "professional"

**Comment by ammatwain** [comment] 2023-07-13 06:30
I'll give it a shot, just to brainstorm. Since the duration of the notes is a numerical value, wouldn't it be more accurate to think of them as aligned to the right? (Sorry, I have no idea where they are aligned, I assume it's to the left based on how the issue looks)

**Comment by sschmidTU** [comment] 2023-07-13 08:07
I'm guessing the solution will be in `stave.getNoteStartX()`. We probably need to tell the other staves to shift their startX, when they have clefs and key signatures with different widths.

**Comment by sschmidTU** [comment] 2023-07-13 10:56
It looks like the Vexflow solution is in https://github.com/0xfe/vexflow/pull/1390.
I'll go about porting it to our VexflowPatch!

**Comment by sschmidTU** [comment] 2023-07-13 18:55
aaaaaand done, see #1427!

before:
<img width="219" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/c4dac616-e3e9-490e-a669-fcdc78b5146d">

after:
<img width="249" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/8dfd6e84-9e64-4af9-885a-f9a2c4df5c21">

**Closed** 2023-07-13 19:35 UTC

**Comment by sschmidTU** [comment] 2023-07-14 17:11
Fix is released in OSMD 1.8.1!
