### ISSUE TITLE
 Is there any way to speed up musicxml rendering？

### ISSUE THREAD

**Issue by luckyguygx** [opensheetmusicdisplay/opensheetmusicdisplay#1537] opened 2024-04-07 07:23 UTC
On some low-end phones, the rendering of large music is slow. Is there any way to speed up musicxml rendering？

**Comment by sschmidTU** [comment] 2024-04-07 09:01
No easy way. Unfortunately large music takes time to render, especially on slow phones.
This is a duplicate of #937, and you can see a very complex performance improvement we already did in #1158.
You can try using WebGL, though it might be slower:
```js
osmd.EngravingRules.AlwaysSetPreferredSkyBottomLineBackendAutomatically = false;
osmd.EngravingRules.DisableWebGLInFirefox = false;
osmd.EngravingRules.DisableWebGLInSafariAndIOS = false;
osmd.EngravingRules.PreferredSkyBottomLineBatchCalculatorBackend = 1;
```

Last time I checked, WebGL was slower on iOS and in Firefox, but who knows, maybe they improved their WebGL implementation.

Otherwise, there is unfortunately no easy solution currently.

**Comment by luckyguygx** [comment] 2024-04-07 09:01
邮件收到了

**Closed by sschmidTU** 2024-04-07 09:01 UTC
