### ISSUE TITLE
Connection between VoiceEntry and StaveNote

### ISSUE THREAD

**Issue by dmecke** [opensheetmusicdisplay/opensheetmusicdisplay#193] opened 2018-01-20 18:47 UTC
Hi there,

first of all: thank you very much for your effort in this project. It is very much appreciated! Also before my question: I am an absolute newbie to sheet music, so please forgive my missing knowledge.

I am working on a tool / game, that displays a song, highlights the next note to play and moves on when the user pressed the correct keys on a midi connected device. This works very well with ABC notation (http://abcnotation.com/), but this system has it's limitations. That's why I'd like to try it with OpenSheetMusicDisplay / VexFlow / MusicXML.

I found #125 and #179 and debugged my way through to be able to colorize single notes with something like this:
```
let measure = 0;
let note = 0;
let tickable = this.osmd.graphic.measureList[measure][0].vfVoices[1].tickables[note];
tickable.setStyle({ fillStyle: 'red', strokeStyle: 'red' });
```

I also find a very nice way to check the current note to play against the midi input with something like this: (I simply convert the midi code to a halfTone and compare them)
```
let voiceEntries = this.osmd.sheet.Staves[0].voices[0].VoiceEntries;
voiceEntries.forEach(voiceEntry => console.log(entry.Notes[0].halfTone));
```

Now my problem is, that I cannot find a connection between that `VoiceEntry` class which is part of OpenSheetMusicDisplay and the `StaveNote` class from VexFlow. That connection would enable me to easily colorize the current note.

At some points in the code I found some kind of instance ids, so my hope is that you do some kind of mapping from your data to VexFlows, which I could use...
Any help is very appreciated!

**Comment by bneumann** [comment] 2018-01-20 19:45
Sounds like a duplicate of #179 to me.

**Comment by dmecke** [comment] 2018-01-20 19:53
Yes, I found the way to colorize the note with the help of your code snippet in that ticket. So that part works.

But what I would need is a connection between the ```StaveNote``` objects that I can apply the color on and the ```VoiceEntry``` objects of OpenSheetMusicDisplay, because that is where I have the information about the current note that has to be played.

**Comment by matt-uib** [comment] 2018-01-20 20:54
There is no direct link, but the StaffEntry, holding the voiceEntries, has the connection:
See VexFlowStaffEntry.ts
'''
export class VexFlowStaffEntry extends GraphicalStaffEntry {
    constructor(measure: VexFlowMeasure, sourceStaffEntry: SourceStaffEntry, staffEntryParent: VexFlowStaffEntry) {
        super(measure, sourceStaffEntry, staffEntryParent);
    }

    // The Graphical Notes belonging to this StaffEntry, sorted by voiceID
    public graphicalNotes: { [voiceID: number]: GraphicalNote[]; } = {};
    // The corresponding VexFlow.StaveNotes
    public vfNotes: { [voiceID: number]: Vex.Flow.StaveNote; } = {};
'''
The first member '''graphicalNotes''' gives you a list of GraphicalNotes for a given voice index.
These GraphicalNotes point to the same Notes that will be in VexFlowStaffEntry.SourceStaffEntry.VoiceEntries.
We separated here the "Source" objects from the "Graphical" objects. Source is more the musical information from xml. Graphical is for layouting and rendering (we typically don't use any layout coords from xml, but re-layout newly)
With the second member '''vfNotes''' and the same voice index you get one VexFlow StaveNote representing these GraphicalNotes in VexFlow.
It makes actually sense and is already planned to add a GraphicalVoiceEntry in a future refactoring to make this more straight forward.

**Comment by dmecke** [comment] 2018-01-20 21:29
Cool! Thank you very much, that's exactly what I was looking for!

**Closed** 2018-01-20 21:36 UTC

**Comment by impactcolor** [comment] 2018-03-23 18:40
@dmecke, hi do you have any example on how you were able to color individual staff notes?

**Comment by bneumann** [comment] 2018-03-23 18:50
Hi @impactcolor, please see #207. We are currently not able to color individual notes the way vexflow offers it. But I will investigate next week.

**Comment by impactcolor** [comment] 2018-04-13 06:27
@bneumann where you able to investigate into this?

**Comment by sschmidTU** [comment] 2018-10-23 16:02
@dmecke @impactcolor maybe not relevant for you anymore, but we read and display color from XML now, see #434. (so far for note heads, stems, flags and beams)

**Comment by impactcolor** [comment] 2018-10-23 17:00
Thank you for the heads up, will check it out.  @sschmidTU
