### ISSUE TITLE
Cross Stave Notes Wrong x-position (shifted)

### ISSUE THREAD

**Issue by zhongyita** [opensheetmusicdisplay/opensheetmusicdisplay#1062] opened 2021-09-17 09:22 UTC
some part display incorrect as below: 
![image](https://user-images.githubusercontent.com/35086572/133758877-b90314a2-166e-43ec-8477-bcd0ea04746d.png)

It happens in 6th measure of 24-short.xml which put in attach files.
[24-short.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7184457/24-short.zip)

**Comment by sschmidTU** [comment] 2021-09-21 22:02
This is fixed now:
![image](https://user-images.githubusercontent.com/33069673/134253361-aa750074-be15-49d9-ba53-2f0b9f16fcab.png)

Here's a simplified sample for testing:
![image](https://user-images.githubusercontent.com/33069673/134253569-bfd2deff-75f0-4474-9073-8280e8fdd7b3.png)
[cross-quarters2.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7206519/cross-quarters2.zip)

However, this still needs regression testing, and also, we are currently looking at a related issue with cross hand notes that may need some adjustments in the implementation.

**Comment by sschmidTU** [comment] 2021-09-21 23:16
This also improves 3 other samples, while one problem in another sample is more pronounced now.

In Dichterliebe, this improves many measures immensely, especially measure 5:
![image](https://user-images.githubusercontent.com/33069673/134258060-6bc8467c-d6c9-49bb-a1e3-de992a9412e5.png)
![image](https://user-images.githubusercontent.com/33069673/134258002-7376398b-618a-488b-8c15-c045f23970f4.png)

In Haydn - Concertante, this fixes an overlap:
![image](https://user-images.githubusercontent.com/33069673/134257125-546de3d8-44eb-47ec-a1f3-d5ca4e1bfab7.png)
![image](https://user-images.githubusercontent.com/33069673/134257185-a6f327f4-ac12-4e6e-a450-ba4d33189f50.png)

There's just one problem: The beginning of Elite Syncopations (Joplin).
It was always there, but it's more pronounced now (simplified sample):
![image](https://user-images.githubusercontent.com/33069673/134259611-1d56cca9-a14e-4b7c-9892-002eb7570616.png)
![image](https://user-images.githubusercontent.com/33069673/134259579-3c14cd3e-fb29-45e3-8a5d-265c2279b2ac.png)
The last 3 notes F, G, A should be simultaneous.
[syncopations_m2.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7206774/syncopations_m2.musicxml.zip)

The problem is that it calculates a ghost note of 3/16th length for the lower notes now.
I'll investigate.

**Comment by matt-uib** [comment] 2021-09-22 08:44
Looks good - seems the right track!

**Comment by sschmidTU** [comment] 2021-09-23 15:48
Elite Syncopations is now fixed, too.

<img src="https://user-images.githubusercontent.com/33069673/134259579-3c14cd3e-fb29-45e3-8a5d-265c2279b2ac.png" height="130"/>
<img src="https://user-images.githubusercontent.com/33069673/134539578-7afce991-d0af-4c44-bcb2-c73b385ba07f.png" height="145"/>

The issue was that for ghost notes (for vexflow) of a certain duration (Fraction), we only created a single ghost note.
But some fractions like 5/16 can't be represented by a single note, so we have to add multiple notes (a quarter and a 16th note).
(e.g. for a fraction like 5/16th (5 16th notes), a dotted quarter would be too long, while a dotted 8th can never be longer than a quarter because each dot adds half of the value of the previous dot/note).

With this, the whole issue fix on the branch looks clean and will be merged.

**Comment by sschmidTU** [comment] 2021-09-23 16:46
@zhongyita This is now fixed and merged. A new OSMD version should be out soon.

**Closed** 2021-09-23 16:45 UTC
Labels: bug

**Comment by zhongyita** [comment] 2021-09-24 03:33
Tested and it works now. Nice.

**Comment by sschmidTU** [comment] 2021-12-02 12:13
Fixed a different bug related to this, see commit above.
After:
![image](https://user-images.githubusercontent.com/33069673/144418643-2e26574b-05c1-450a-bac4-57989e14c872.png)

Before:
![image](https://user-images.githubusercontent.com/33069673/144418606-0be8e930-bb94-4c00-9e4b-85bb0412b783.png)

**Comment by sschmidTU** [comment] 2023-08-14 19:31
Fixed an issue with x-alignment for tab notes when more than one ghost note was required.
When e.g. a ghost note of 5/16 is required, you can't represent that with a single note (since a dotted 8th is 6/16).
And so far we only added a single ghost note for tabs.

before:
<img width="233" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/711689eb-117e-494b-bc85-a52480cac7d0">

after:
<img width="255" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/dd84a1df-e03f-48ff-9d63-88fcf6dc42e5">

visual regression diffs:
[diff_tabs-x-alignment-fix-multiple-ghostnotes.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12338933/diff_tabs-x-alignment-fix-multiple-ghostnotes.zip)
(only `test_slide_glissando.musicxml` changed/fixed)
