### ISSUE TITLE
Full rest x position error

### ISSUE THREAD

**Issue by TheBrightestStarInTheNightSky** [opensheetmusicdisplay/opensheetmusicdisplay#605] opened 2019-10-28 07:59 UTC
When there is a complete rest in a bar, the x position of the obtained complete rest is incorrect. If it is not a complete rest, but a two-minute and four-minute rest, the x position of the obtained rest is correct. I get rest position method is osmd.graphic.verticalGraphicalStaffEntryContainers[i].staffEntries[j].graphicalVoiceEntries[k].notes[l].boundingBox.absolutePosition.x * 10 , do excuse me such access is there a problem?

**Comment by lkkmm** [comment] 2019-11-05 09:12
Whether to solve?

**Comment by sschmidTU** [comment] 2019-11-05 10:07
To solve, or not to solve, that is the question:
Whether 'tis nobler in the mind to suffer
The slings and arrows of outrageous fortune,
Or to take arms against a sea of troubles
And by opposing end them.

Sorry, had to.
Of course we want to solve this, we just have to prioritize, and right now the OSMD team members are a bit busy. We also hope that at some time other people can contribute and solve a few issues.

**Comment by sschmidTU** [comment] 2019-11-05 15:28
#616 is a duplicate of this, but has a good screenshot and an idea for a solution.

**Comment by sschmidTU** [comment] 2019-12-03 19:10
continued in #609 (duplicate)

**Closed** 2019-12-03 19:10 UTC
Labels: duplicate
