### ISSUE TITLE
Suspicious errors/warnings 

### ISSUE THREAD

**Issue by borismus** [opensheetmusicdisplay/opensheetmusicdisplay#240] opened 2018-04-16 20:56 UTC
If I import { OSMD } from "opensheetmusicdisplay", I get warnings in webpack build output:

```
WARNING in ./node_modules/typescript-collections/dist/lib/Dictionary.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/lib/Dictionary.ts': Error: Can't resolve '../../src/lib/Dictionary.ts' in '/usr/local/google/home/smus/Projects/score-follower/ui/node_modules/typescript-collections/dist/lib'
 @ ./node_modules/opensheetmusicdisplay/dist/src/MusicalScore/Graphical/GraphicalMusicSheet.js 11:19-72
 @ ./node_modules/opensheetmusicdisplay/dist/src/OSMD/OSMD.js
 @ ./src/index.ts

WARNING in ./node_modules/typescript-collections/dist/lib/util.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/lib/util.ts': Error: Can't resolve '../../src/lib/util.ts' in '/usr/local/google/home/smus/Projects/score-follower/ui/node_modules/typescript-collections/dist/lib'
 @ ./node_modules/typescript-collections/dist/lib/Dictionary.js 3:11-28
 @ ./node_modules/opensheetmusicdisplay/dist/src/MusicalScore/Graphical/GraphicalMusicSheet.js
 @ ./node_modules/opensheetmusicdisplay/dist/src/OSMD/OSMD.js
 @ ./src/index.ts
```

Also, webpack complains about entrypoint sizes exceeding limits. Here's the workaround: https://github.com/webpack/webpack/issues/3486

**Comment by bneumann** [comment] 2018-04-17 04:16
So this are actually two things. The second is a duplicate of #231 and already known. The workaround from webpack is basically to disable the warning which I don't like.

The first thing is that webpack does not seem to find the source files which is really weird. Which branch are you using? And which webpack version?

**Comment by bneumann** [comment] 2018-04-17 05:50
I was wondering, if you clone the repo (develop) and hit npm install you should get a valid build. With no warnings whatsoever. Except the size issue of course.
It would help if you can explain your proceedings

**Comment by borismus** [comment] 2018-05-15 20:02
I stopped using this project, switched to musescore. Thanks

**Comment by matt-uib** [comment] 2018-05-15 22:08
All right, thanks for telling us.

**Closed by matt-uib** 2018-05-15 22:08 UTC
