### ISSUE TITLE
Display chords?

### ISSUE THREAD

**Issue by zwiebelspaetzle** [opensheetmusicdisplay/opensheetmusicdisplay#247] opened 2018-05-02 14:10 UTC
OSMD is displaying neither chord names nor fingering charts from scores created in musescore.  Is it possible to display chords?

**Comment by bneumann** [comment] 2018-05-03 15:02
Duplicate of #148

**Closed by bneumann** 2018-05-03 15:02 UTC

**Comment by bneumann** [comment] 2018-05-03 15:04
We are currently, as in just while I am typing, preparing a new release. Your request should be integrated  in 0.3.0
