### ISSUE TITLE
Cross stave beams not connected

### ISSUE THREAD

**Issue by hanghang2** [opensheetmusicdisplay/opensheetmusicdisplay#1524] opened 2024-03-15 10:38 UTC
The two are connected in MuseScore, but not in OSMD. Is there a solution to this?
![lQLPJwNJIYoX7kHNAULNAYCwKL7TwFCaUfIF4glhwCcfAQ_384_322](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/25996792/64dc4fe7-75c7-46cc-a7cc-85fef073c327)
![lQLPKeRVz7PXPkHNAavNAhGwXnkOevqNjmkF4glhwCcfAA_529_427](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/25996792/2aaf1d5b-c8a6-4f2c-bfaa-c5c18b801f17)

**Comment by sschmidTU** [comment] 2024-03-15 10:49
duplicate of #624.
Not possible in Vexflow.

**Closed by sschmidTU** 2024-03-15 10:49 UTC
Labels: duplicate

**Comment by rvilarl** [comment] 2024-03-16 19:06
VexFlow 4 and 5 supports it. A reason to upgrade. ;)

**Comment by sschmidTU** [comment] 2024-03-16 21:36
Nice. Yeah, it's planned, it's just going to be a lot of work, also porting over our remaining custom patches.
