### ISSUE TITLE
iOS memory leak

### ISSUE THREAD

**Issue by Z1X1Z** [opensheetmusicdisplay/opensheetmusicdisplay#1411] opened 2023-06-22 18:33 UTC
When I render the score repeatedly to change measure and note colors, on iOS a canvas element called osmdCanvasVexFlowBackendCanvas1 appears to be duplicated in the Safari memory profiler.  This memory leak is causing the site to crash after enough renders (how many renders depends on how much of the score is rendered each time).  I've tried removing and deleting the element with getElementById("osmdCanvasVexFlowBackendCanvas1") .remove and then =null and the same with osmd.canvas but it doesn't seem to respond.  The bug is only on iOS, not Android or Mac.  Any ideas of how to fix this?

**Comment by sschmidTU** [comment] 2023-06-22 18:45
Interesting. I assume this also happens in our [public demo](https://opensheetmusicdisplay.github.io/demo), right? (makes it easier for us to reproduce)
It's strange because we have code to clear the backends on re-render, which seems to be working outside of iOS.

Maybe we need to do more and e.g. delete all the references (set to undefined) before creating a new backend.
We could also try clearing the canvas with backend.clear() (at least on iOS).

**Comment by Z1X1Z** [comment] 2023-06-22 23:56
I just checked in the demo, and rerendering does leak, adding new canvas elements, only they don't have an id.

**Comment by sschmidTU** [comment] 2023-06-23 08:07
This might be due to the way Vexflow copies the SVG onto a canvas, if I recall correctly (as if you switch from SVG to Canvas, you need to re-render, though in the current state of the demo we do anyways).
I'll take a look. Hopefully this can be fixed with some more deallocation / clearing / setting things undefined. Or maybe it's also just a temporary bug in the latest iOS versions that will be fixed soon, it happens.

**Comment by Z1X1Z** [comment] 2023-07-19 22:27
I have a guess as to a fix.  So I once had a memory leak bug with an animated verbose output using innerHTML and what ended up solving it was declaring the object in the .html file: a la  <div id="textWindow">LOVE</div>, some innerContent such as here, "LOVE" is required to get the object appended on load.  If you could move the leaking elements declaration into a once for all declaration directly in the html.  I have no idea if this is possible so far as types go, but maybe if it was anchored directly in the .html content with something like <canvas id="VEXFlowCanvas"> and then pull a pull with
var canvas = document.getElementById("VEXFlowCanvas").
  It seems like one potential answer if it can be implemented.  Though for one thing that bug was on osX mac too, and this one is only on iOS.  So it may not work.

**Comment by sschmidTU** [comment] 2023-07-19 22:34
Interesting, doesn't hurt to try it. By the way, if you can also try some things, that would be highly appreciated.
My iPhone is pretty old and I'm not mainly an iPhone/Mac user, so debugging iOS is a bit cumbersome, but I'll eventually get to it and also try tools like browserstack. But any help would be a big help in case of iOS debugging.

**Comment by sschmidTU** [comment] 2023-09-19 15:31
This should be fixed now with the 1.8.4 release.
@Z1X1Z Just one question: You were using the Canvas backend, right? Because the SVG backend didn't cause issues for me on iOS (could render ~30 times in a row), and also only Canvas backend creates named `osmdCanvasVexFlowBackendCanvas1` and so on.

In any case: Can you test that the issue is fixed now in our [public demo](https://opensheetmusicdisplay.github.io/demo/)?
It should be though, so unless someone answers otherwise, I'll consider this fixed.

With my old iPhone, before 1.8.4, when I chose Canvas backend, the site crashed after re-rendering around 5 times.
With 1.8.4, it doesn't crash anymore.

I've consulted these two resources, especially the second one for the solution:
https://stackoverflow.com/questions/58438276/cannot-remove-canvas-elements-from-memory-that-are-created-but-never-appended-to
https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12
(the solution I settled for is a slight simplification of [this one](https://stackoverflow.com/a/64557130/10295942), without waiting for the animation)

**Closed by sschmidTU** 2023-09-19 15:31 UTC

**Comment by Z1X1Z** [comment] 2023-10-31 20:57
I checked on the online demo on iPad and it's still there, maybe a hundred or more reloads.  You can profile the memory in the safari developer tools described at https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac

I think you need to enable memory profiling in safari profiler too!

**Comment by sschmidTU** [comment] 2023-10-31 21:01
It might be temporary bugs in the new iOS updates etc, as there have been I think 2 other new bugs reported recently that are exclusive to iOS, which used to be completely fixed before, too. Unfortunately there's a chance that it's simply an iOS bug. Fortunately it might soon be fixed on its own as well.
But of course it would be great to look into it as well and try to find fixes.

**Comment by Z1X1Z** [comment] 2023-11-02 20:43
So I tried my suggested fix of anchoring the canvas.

in the HTML:

   div id="osmdCanvas"
                div id="anchorDiv"
            canvas id="osmdCanvasAnchor" 
/canvas
/div
  /div

The github editor didn't like the <> so I took them out.

in vexFlowBackend.ts:
 ```
  public initialize(container: HTMLElement, zoom: number): void {
        this.zoom = zoom;
        this.canvas =document.getElementById("osmdCanvasAnchor");
        if (!this.graphicalMusicPage) {
            this.graphicalMusicPage = new GraphicalMusicPage(undefined);
            this.graphicalMusicPage.PageNumber = 1;
        }
        this.inner = document.getElementById("anchorDiv");
        this.inner.style.position = "relative";
        this.canvas.style.zIndex = "0";
       
        this.renderer = new VF.Renderer(this.canvas, this.getVexflowBackendType());
        this.ctx = <VF.CanvasContext>this.renderer.getContext();
    }

```
in cursor.ts changed this:
`          this.container = document.getElementById("osmdCanvasPage" + newPageNumber);`
to this:
`          this.container = document.getElementById("anchorDiv");`


removed from OpenSheetMusic.ts:

```

            if (this.drawer.Backends[0]) {
                this.drawer.Backends[0].removeAllChildrenFromContainer(this.container);
            }
```

Hopefully you can sort something out!
