### ISSUE TITLE
Interface Note click event

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1212] opened 2022-08-22 09:39 UTC
I want to click the note on the interface and get the information of the current note. What do I need to do

**Comment by sschmidTU** [comment] 2022-08-23 18:33
I assume you're not using the (sponsor) OSMD Audio Player, in that case duplicate of #857.

**Closed by sschmidTU** 2022-08-23 18:33 UTC
